<script setup lang="ts">
const props = defineProps<{
    form: any
    method?: 'post' | 'put'
}>()

const form = props.form
const method = props.method
</script>

<template>
    <div v-if="method === 'put'" class="space-y-4">
        <h2 class="text-lg font-semibold border-b pb-2">Payment References</h2>
        <p class="text-sm text-gray-500">
            These are typically system-generated by payment processors.
        </p>

        <div class="grid grid-cols-2 gap-4">
            <div>
                <label class="block text-sm font-medium mb-1">Payment Intent ID</label>
                <input
                    v-model="form.payment_intent_id"
                    type="text"
                    class="w-full border rounded px-3 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500"
                    placeholder="pi_..."
                />
                <p v-if="form.errors.payment_intent_id" class="text-red-500 text-sm mt-1">
                    {{ form.errors.payment_intent_id }}
                </p>
            </div>

            <div>
                <label class="block text-sm font-medium mb-1">Charge ID</label>
                <input
                    v-model="form.charge_id"
                    type="text"
                    class="w-full border rounded px-3 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500"
                    placeholder="ch_..."
                />
                <p v-if="form.errors.charge_id" class="text-red-500 text-sm mt-1">
                    {{ form.errors.charge_id }}
                </p>
            </div>
        </div>

        <div class="grid grid-cols-2 gap-4">
            <div>
                <label class="block text-sm font-medium mb-1">Stripe Payment Intent</label>
                <input
                    v-model="form.stripe_payment_intent"
                    type="text"
                    class="w-full border rounded px-3 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500"
                    placeholder="pi_..."
                />
                <p v-if="form.errors.stripe_payment_intent" class="text-red-500 text-sm mt-1">
                    {{ form.errors.stripe_payment_intent }}
                </p>
            </div>

            <div>
                <label class="block text-sm font-medium mb-1">Stripe Invoice ID</label>
                <input
                    v-model="form.stripe_invoice_id"
                    type="text"
                    class="w-full border rounded px-3 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500"
                    placeholder="in_..."
                />
                <p v-if="form.errors.stripe_invoice_id" class="text-red-500 text-sm mt-1">
                    {{ form.errors.stripe_invoice_id }}
                </p>
            </div>
        </div>
    </div>
</template>